
services:
  backend:
    build: ./backend/Reto5
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/vacantes_BBDD_2025_RETO?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SECRET=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      - JWT_EXPIRATION=3600000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      - db
    networks:
      - app-network
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:8.0
    command: --authentication_policy=caching_sha2_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vacantes_BBDD_2025_RETO
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    

volumes:
  db_data:

networks:
  app-network:
    driver: bridge